spring.application.name=admin
server.port=8080
# URL de la conexión local a tu PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/gimnasio_db
# El usuario por defecto que creó el instalador
spring.datasource.username=postgres
# REEMPLAZA AQUÍ: Pon la contraseña exacta que digitaste en el Paso 1
spring.datasource.password=Post*10sql

# Configuración de Hibernate para auto-crear las tablas del gimnasio
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
